# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED from types/tickets.schema.json — do not edit manually.
# Regenerate with: make generate-types

# generated by datamodel-codegen:
#   filename:  tickets.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class ResponseType(StrEnum):
    """
    Expected response type: 'approval' shows approve/deny buttons, 'free_text' shows a reply textarea.
    """

    approval = "approval"
    free_text = "free_text"


class TicketStatus(StrEnum):
    """
    Ticket lifecycle status.
    """

    open = "open"
    assigned = "assigned"
    approved = "approved"
    denied = "denied"
    replied = "replied"
    closed = "closed"


class TicketPriority(StrEnum):
    """
    Ticket priority level.
    """

    high = "high"
    medium = "medium"
    low = "low"


class TicketComment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    author: str = Field(..., description="Comment author (user alias or 'agent').")
    text: str = Field(..., description="Comment body.")
    timestamp: str = Field(..., description="ISO timestamp.")


class Ticket(BaseModel):
    """
    Single source of truth for ticket management types. Generated into TS and Python via `make generate-types`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ticket_id: str = Field(
        ..., description="Unique ticket identifier (e.g. TKT-A1B2C3D4)."
    )
    title: str = Field(..., description="Short summary of the ticket.")
    description: str = Field(
        ..., description="Detailed description of the issue or request."
    )
    status: TicketStatus
    priority: TicketPriority
    created_by: str | None = Field(
        None, description="User or agent that created the ticket."
    )
    assigned_to: str | None = Field(
        None, description="Person or team assigned to the ticket."
    )
    case_id: str | None = Field(
        None, description="Related ERP case ID for correlation (doc#item format)."
    )
    category: str | None = Field(
        None, description="Ticket category (e.g. approval_request, exception, inquiry)."
    )
    response_type: ResponseType | None = Field(
        "approval",
        description="Expected response type: 'approval' shows approve/deny buttons, 'free_text' shows a reply textarea.",
    )
    resolution: str | None = Field(None, description="Resolution notes.")
    comments: list[TicketComment] | None = Field(
        None, description="Chronological list of comments on the ticket."
    )
    created_at: str = Field(..., description="ISO timestamp of creation.")
    updated_at: str = Field(..., description="ISO timestamp of last update.")
