# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED from types/cases.schema.json — do not edit manually.
# Regenerate with: make generate-types

# generated by datamodel-codegen:
#   filename:  cases.schema.json

from __future__ import annotations

from enum import Enum, StrEnum

from pydantic import BaseModel, ConfigDict, Field


class UserRating(Enum):
    """
    Case-level resolution quality rating from a human reviewer.
    """

    positive = "positive"
    negative = "negative"


class Domain(StrEnum):
    """
    Skill domain — aligns with skills/ folder names.
    """

    finance_ap = "finance_ap"


class Priority(StrEnum):
    high = "high"
    medium = "medium"
    low = "low"


class CaseStatus(StrEnum):
    detected = "detected"
    processing = "processing"
    awaiting_human_input = "awaiting_human_input"
    sap_updated = "sap_updated"
    complete = "complete"
    manual_review_required = "manual_review_required"


class Trigger(StrEnum):
    """
    What initiated an agent invocation.
    """

    poller = "poller"
    webhook_ses = "webhook-ses"
    webhook_slack = "webhook-slack"
    webhook_jira = "webhook-jira"
    webhook_servicenow = "webhook-servicenow"
    ticket_action = "ticket-action"
    manual = "manual"


class Type(StrEnum):
    text = "text"
    tool = "tool"


class TraceSegment(BaseModel):
    type: Type
    content: str | None = None
    tool_name: str | None = None
    tool_input: str | None = None
    tool_result: str | None = None


class AgentTrace(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trace_id: str
    timestamp: str
    trigger: Trigger | None = Field(None, description="What initiated this invocation.")
    prompt: str | None = None
    outcome: str | None = Field(
        None,
        description="Invocation result: complete, stopped, cancelled, error, disconnected.",
    )
    segments: list[TraceSegment]


class WorkItem(BaseModel):
    """
    Single source of truth for ERP automation work item types. Generated into TS and Python via `make generate-types`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    document_number: str = Field(
        ..., description="SAP document number (e.g. supplier invoice). Partition key."
    )
    item_id: str = Field(
        ..., description="Item identifier within the document. Sort key."
    )
    domain: Domain = Field(..., description="Skill domain this item belongs to.")
    process_type: str = Field(
        ...,
        description="Specific process type for skill routing, e.g. invoice_matching, price_variance.",
    )
    title: str | None = Field(None, description="Human-readable summary for display.")
    description: str | None = Field(None, description="Short detail text.")
    priority: Priority | None = None
    status: CaseStatus
    created_at: str
    updated_at: str
    company_code: str | None = Field(None, description="SAP company code.")
    supplier_number: str | None = Field(None, description="AP: Supplier/vendor number.")
    amount: float | None = Field(None, description="AP: Transaction amount.")
    currency: str | None = Field(None, description="AP: Currency code (e.g. USD).")
    exception_type: str | None = Field(None, description="AP: Payment blocking reason.")
    document_date: str | None = Field(None, description="AP: Invoice document date.")
    posting_date: str | None = Field(None, description="AP: Posting date.")
    external_reference: str | None = Field(
        None, description="AP: Supplier's own invoice ID."
    )
    purchase_order: str | None = Field(
        None, description="AP: PO number referenced on the invoice line item."
    )
    po_line_item: str | None = Field(None, description="AP: PO line item number.")
    invoice_quantity: float | None = Field(
        None, description="AP: Invoiced quantity in PO unit."
    )
    inquiry_sent_at: str | None = Field(
        None,
        description="ISO timestamp of an outbound inquiry, if the workflow sent one.",
    )
    ttl: int | None = None
    user_rating: UserRating | None = Field(
        None, description="Case-level resolution quality rating from a human reviewer."
    )
    user_rating_comment: str | None = Field(
        None, description="Optional comment explaining the rating."
    )
    user_rating_at: str | None = Field(
        None, description="ISO timestamp of when the rating was submitted."
    )
    agent_traces: list[AgentTrace] | None = Field(
        None, description="Historical agent thought-process traces, one per invocation."
    )
